#!/bin/bash

export MONITOR_BASE=$PWD/..
export ZMQ=$MONITOR_BASE/external/zeromq-install
export MSGPACK=$MONITOR_BASE/external/msgpack-install

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ZMQ/lib:$MSGPACK/lib
